services:
  astrotemplate2024:
    container_name: astrotemplate2024
  # image may be omitted from a Compose file as long as a build section is declared. 
    # image: astrotemplate2024
    build:
      context: .  #build context is root dir and sub-dirs of compose file
      dockerfile: ./Dockerfile
    init: true  # creates a init PID1 that can clean up zombies and orphans, also passes termination signals to node (node wasn't designed to be a init system)
    # defines environment variables set in the container
    secrets:
      - cert_key
      - cert_cert
    environment:
      - NODE_ENV=production
      - SERVER_KEY_PATH=/run/secrets/cert_key
      - SERVER_CERT_PATH=/run/secrets/cert_cert
    command: ["node", "./dist/server/entry.mjs"]
    # command: ["sh", "-c", "SERVER_KEY_PATH=/run/secrets/cert_key SERVER_CERT_PATH=/run/secrets/cert_cert node ./dist/server/entry.mjs"]
      
    # port mapping (HOST:CONTAINER) TODO: for server env, no host mapping, just expose container port for Caddy
    ports:
      - 4321:4321
    # expose:  #use instead of ports when in server env example
      # - 4321
    # networks:
      # - caddy_network

# the network has to be mannually created via cli if multiple sevices will use it but have their own docker compose files
# docker network create caddy_network 
# networks:
  # caddy_network:
    # external: true
    # driver: bridge

secrets:
  cert_key:
    file: ./private/cert-key.pem
  cert_cert:
    file: ./private/cert.pem
# SERVER_KEY_PATH=./private/key.pem SERVER_CERT_PATH=./private/cert.pem node ./dist/server/entry.mjs