version: '3.4'

services:
  astrotemplate2024:
    image: astrotemplate2024
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4321:4321
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
